# Stage 1: Build
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

# Accept Supabase env vars at build time
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_USER_SERVICE_URL
ARG NEXT_PUBLIC_APPLICATION_SERVICE_URL
ARG NEXT_PUBLIC_GRACE_SERVICE_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_USER_SERVICE_URL=$NEXT_PUBLIC_USER_SERVICE_URL
ENV NEXT_PUBLIC_APPLICATION_SERVICE_URL=$NEXT_PUBLIC_APPLICATION_SERVICE_URL
ENV NEXT_PUBLIC_GRACE_SERVICE_URL=$NEXT_PUBLIC_GRACE_SERVICE_URL

RUN npm run build

# Stage 2: Run
FROM node:18

WORKDIR /app

COPY --from=builder /app ./
RUN npm install --omit=dev

EXPOSE 3000

CMD ["npm", "start"]
